// Generated by gencpp from file find_object_2d/Point_id.msg
// DO NOT EDIT!


#ifndef FIND_OBJECT_2D_MESSAGE_POINT_ID_H
#define FIND_OBJECT_2D_MESSAGE_POINT_ID_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace find_object_2d
{
template <class ContainerAllocator>
struct Point_id_
{
  typedef Point_id_<ContainerAllocator> Type;

  Point_id_()
    : id(0)
    , point()  {
    }
  Point_id_(const ContainerAllocator& _alloc)
    : id(0)
    , point(_alloc)  {
  (void)_alloc;
    }



   typedef int16_t _id_type;
  _id_type id;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _point_type;
  _point_type point;




  typedef boost::shared_ptr< ::find_object_2d::Point_id_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::find_object_2d::Point_id_<ContainerAllocator> const> ConstPtr;

}; // struct Point_id_

typedef ::find_object_2d::Point_id_<std::allocator<void> > Point_id;

typedef boost::shared_ptr< ::find_object_2d::Point_id > Point_idPtr;
typedef boost::shared_ptr< ::find_object_2d::Point_id const> Point_idConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::find_object_2d::Point_id_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::find_object_2d::Point_id_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace find_object_2d

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'find_object_2d': ['/home/adrianna/Progr/ROS/ws/src/find-object/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::find_object_2d::Point_id_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::find_object_2d::Point_id_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::find_object_2d::Point_id_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::find_object_2d::Point_id_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::find_object_2d::Point_id_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::find_object_2d::Point_id_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::find_object_2d::Point_id_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d929924128f786e041a67cac2d045dbd";
  }

  static const char* value(const ::find_object_2d::Point_id_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd929924128f786e0ULL;
  static const uint64_t static_value2 = 0x41a67cac2d045dbdULL;
};

template<class ContainerAllocator>
struct DataType< ::find_object_2d::Point_id_<ContainerAllocator> >
{
  static const char* value()
  {
    return "find_object_2d/Point_id";
  }

  static const char* value(const ::find_object_2d::Point_id_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::find_object_2d::Point_id_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# publish position of the recognized objects \n\
int16 id\n\
geometry_msgs/Point point\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::find_object_2d::Point_id_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::find_object_2d::Point_id_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Point_id_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::find_object_2d::Point_id_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::find_object_2d::Point_id_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int16_t>::stream(s, indent + "  ", v.id);
    s << indent << "point: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.point);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FIND_OBJECT_2D_MESSAGE_POINT_ID_H
