// Generated by gencpp from file find_object_2d/PointObjects.msg
// DO NOT EDIT!


#ifndef FIND_OBJECT_2D_MESSAGE_POINTOBJECTS_H
#define FIND_OBJECT_2D_MESSAGE_POINTOBJECTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <find_object_2d/Point_id.h>

namespace find_object_2d
{
template <class ContainerAllocator>
struct PointObjects_
{
  typedef PointObjects_<ContainerAllocator> Type;

  PointObjects_()
    : object()  {
    }
  PointObjects_(const ContainerAllocator& _alloc)
    : object(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::find_object_2d::Point_id_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::find_object_2d::Point_id_<ContainerAllocator> >::other >  _object_type;
  _object_type object;




  typedef boost::shared_ptr< ::find_object_2d::PointObjects_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::find_object_2d::PointObjects_<ContainerAllocator> const> ConstPtr;

}; // struct PointObjects_

typedef ::find_object_2d::PointObjects_<std::allocator<void> > PointObjects;

typedef boost::shared_ptr< ::find_object_2d::PointObjects > PointObjectsPtr;
typedef boost::shared_ptr< ::find_object_2d::PointObjects const> PointObjectsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::find_object_2d::PointObjects_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::find_object_2d::PointObjects_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace find_object_2d

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'find_object_2d': ['/home/adrianna/Progr/ROS/ws/src/find-object/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::find_object_2d::PointObjects_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::find_object_2d::PointObjects_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::find_object_2d::PointObjects_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::find_object_2d::PointObjects_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::find_object_2d::PointObjects_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::find_object_2d::PointObjects_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::find_object_2d::PointObjects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3b586c352257d5c7f5223390e99efc91";
  }

  static const char* value(const ::find_object_2d::PointObjects_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3b586c352257d5c7ULL;
  static const uint64_t static_value2 = 0xf5223390e99efc91ULL;
};

template<class ContainerAllocator>
struct DataType< ::find_object_2d::PointObjects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "find_object_2d/PointObjects";
  }

  static const char* value(const ::find_object_2d::PointObjects_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::find_object_2d::PointObjects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# contains an array with previous msg for each recognized obj\n\
Point_id[] object\n\
\n\
================================================================================\n\
MSG: find_object_2d/Point_id\n\
# publish position of the recognized objects \n\
int16 id\n\
geometry_msgs/Point point\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::find_object_2d::PointObjects_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::find_object_2d::PointObjects_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PointObjects_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::find_object_2d::PointObjects_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::find_object_2d::PointObjects_<ContainerAllocator>& v)
  {
    s << indent << "object[]" << std::endl;
    for (size_t i = 0; i < v.object.size(); ++i)
    {
      s << indent << "  object[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::find_object_2d::Point_id_<ContainerAllocator> >::stream(s, indent + "    ", v.object[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FIND_OBJECT_2D_MESSAGE_POINTOBJECTS_H
